Repository networktocode/ntc-templates, pull requests merged in 2019-10, with the labels that each got.

#468 template for show arp in watchguard
  templates/index
  templates/watchguard_firebox_show_arp.template
  tests/test_index_order.py
  tests/watchguard_firebox/show_arp/watchguard_firebox_show_arp.parsed
  tests/watchguard_firebox/show_arp/watchguard_firebox_show_arp.raw
Labels: New Template, changes_requested

#481 Adding Values for route-map names fetch for nxos_sh_ip_bgp_nei
  templates/cisco_nxos_show_ip_bgp_neighbors.template
  tests/cisco_nxos/show_ip_bgp_neighbors/cisco_nxos_show_ip_bgp_neighbors.parsed
  tests/cisco_nxos/show_ip_bgp_neighbors/cisco_nxos_show_ip_bgp_neighbors_with_policy_names.parsed
  tests/cisco_nxos/show_ip_bgp_neighbors/cisco_nxos_show_ip_bgp_neighbors_with_policy_names.raw
Labels: changes_requested, enhancement

#485 Fix mac address table
  templates/cisco_ios_show_mac-address-table.template
Labels: bug

#486 nxos - Template for show route-map command
  templates/cisco_nxos_show_route-map.template
  templates/index
  tests/cisco_nxos/show_route-map/cisco_nxos_show_route-map.parsed
  tests/cisco_nxos/show_route-map/cisco_nxos_show_route-map.raw
Labels: New Template, changes_requested

#364 Cisco IOS show switch detail
  templates/cisco_ios_show_switch_detail.template
  templates/index
  tests/cisco_ios/show_switch_detail/cisco_ios_show_switch_detail1.parsed
  tests/cisco_ios/show_switch_detail/cisco_ios_show_switch_detail1.raw
  tests/cisco_ios/show_switch_detail/cisco_ios_show_switch_detail2.parsed
  tests/cisco_ios/show_switch_detail/cisco_ios_show_switch_detail2.raw
Labels: PR Submitted, waiting_response

#391 Cisco wlc template
  templates/cisco_wlc_ssh_show_client_detail.template
  templates/index
  tests/cisco_wlc_ssh/show_client_detail/cisco_wlc_show_client_detail.parsed
  tests/cisco_wlc_ssh/show_client_detail/cisco_wlc_show_client_detail.raw
Labels: PR Submitted, changes_requested, enhancement

#464 HP Comware `display counters (inbound|outbound) interface`
  templates/hp_comware_display_counters_bound_interface.template
  templates/index
  tests/hp_comware/display_counters_bound_interface/hp_comware_display_counters_bound_interface.parsed
  tests/hp_comware/display_counters_bound_interface/hp_comware_display_counters_bound_interface.raw
Labels: New Template, changes_requested

#489 Cisco NXoS template for "show forwarding ipv4 route"
  templates/cisco_nxos_show_forwarding_ipv4_route.template
  templates/index
  tests/cisco_nxos/show_forwarding_ipv4_route/cisco_nxos_show_forwarding_ipv4_route.parsed
  tests/cisco_nxos/show_forwarding_ipv4_route/cisco_nxos_show_forwarding_ipv4_route.raw
Labels: New Template, changes_requested

#494 Fix netflow and wccp lines
  templates/cisco_ios_show_ip_interface.template
  tests/cisco_ios/show_ip_interface/cisco_ios_show_ip_interface3.parsed
  tests/cisco_ios/show_ip_interface/cisco_ios_show_ip_interface3.raw
  tests/cisco_ios/show_ip_interface/cisco_ios_show_ip_interface4.parsed
  tests/cisco_ios/show_ip_interface/cisco_ios_show_ip_interface4.raw
Labels: bug, changes_requested

#493 Add ruckus_fastiron show arp template
  templates/index
  templates/ruckus_fastiron_show_arp.template
  tests/ruckus_fastiron/show_arp/ruckus_fastiron_show_arp.parsed
  tests/ruckus_fastiron/show_arp/ruckus_fastiron_show_arp.raw
  tests/ruckus_fastiron/show_arp/ruckus_fastiron_show_arp1.parsed
  tests/ruckus_fastiron/show_arp/ruckus_fastiron_show_arp1.raw
  tests/test_index_order.py
Labels: New Template, changes_requested

#492 New Template: cisco_xr_show_ipv6_neighbors
  templates/cisco_xr_show_ipv6_neighbors.template
  templates/index
  tests/cisco_xr/show_ipv6_neighbors/cisco_xr_show_ipv6_neighbors.parsed
  tests/cisco_xr/show_ipv6_neighbors/cisco_xr_show_ipv6_neighbors.raw
Labels: New Template, changes_requested

#466 Paloalto panos arp fix
  templates/paloalto_panos_show_arp_all.template
  tests/paloalto_panos/show_arp_all/paloalto_panos_show_arp_all.parsed
  tests/paloalto_panos/show_arp_all/paloalto_panos_show_arp_all.raw
Labels: New Template, changes_requested, waiting_response

#476 Added BGP up/down time to sh ip bgp summary
  templates/cisco_ios_show_ip_bgp_summary.template
  tests/cisco_ios/show_ip_bgp_summary/cisco_ios_show_ip_bgp_summary.parsed
Labels: changes_requested, enhancement, waiting_response

#401 Issue #384 cisco_asa_show_route - Fix uptime issue
  templates/cisco_asa_show_route.template
  tests/cisco_asa/show_route/cisco_asa_show_route.parsed
  tests/cisco_asa/show_route/cisco_asa_show_route.raw
Labels: bug, changes_requested, waiting_response

#480 Issue 415 cdp
  templates/cisco_ios_show_cdp_neighbors.template
  tests/cisco_ios/show_cdp_neighbors/cisco_ios_show_cdp_neighbors_3.parsed
  tests/cisco_ios/show_cdp_neighbors/cisco_ios_show_cdp_neighbors_3.raw
Labels: Internal Review Requested, bug, changes_requested

#496 Add arista eos show ip helper
  templates/arista_eos_show_ip_helper-address.template
  templates/index
  tests/arista_eos/show_ip_helper-address/arista_eos_show_ip_helper.parsed
  tests/arista_eos/show_ip_helper-address/arista_eos_show_ip_helper.raw
Labels: New Template, changes_requested

#398 New template for Huawei
  templates/huawei_vrp_display_interface_brief.template
  templates/huawei_vrp_display_temperature.template
  templates/index
  tests/huawei_vrp/display_interface_brief/huawei_vrp_display_interface_brief.parsed
  tests/huawei_vrp/display_interface_brief/huawei_vrp_display_interface_brief.raw
  tests/huawei_vrp/display_temperature/huawei_vrp_display_temperature.parsed
  tests/huawei_vrp/display_temperature/huawei_vrp_display_temperature.raw
  tests/test_index_order.py
Labels: PR Submitted, changes_requested, enhancement

#413 Added VRF aware version of `show ip route`
  templates/arista_eos_show_ip_route_vrf.template
  templates/cisco_nxos_show_ip_route_vrf.template
  templates/index
  tests/arista_eos/show_ip_route_vrf/arista_eos_show_ip_route_vrf.parsed
  tests/arista_eos/show_ip_route_vrf/arista_eos_show_ip_route_vrf.raw
  tests/cisco_nxos/show_ip_route_vrf/cisco_nxos_show_ip_route_vrf.parsed
  tests/cisco_nxos/show_ip_route_vrf/cisco_nxos_show_ip_route_vrf.raw
Labels: changes_requested, waiting_response

#449 Arista EOS show vrf to create a simple table of VRF names and RDs
  templates/arista_eos_show_vrf.template
  templates/index
  tests/arista_eos/show_vrf/arista_eos_show_vrf.parsed
  tests/arista_eos/show_vrf/arista_eos_show_vrf.raw
Labels: changes_requested
