Repository networktocode/ntc-templates, pull requests merged in 2019-09, with the labels that each got.

#389 Cisco xr show interfaces duplex and mac for bundle ethernet
  templates/cisco_xr_show_interfaces.template
  tests/cisco_xr/show_interfaces/cisco_xr_show_interfaces.parsed
  tests/cisco_xr/show_interfaces/cisco_xr_show_interfaces.raw
Labels: Internal Review Requested

#399 Cisco IOS - Show ip mroute - Up-time Counters Fix
  templates/cisco_ios_show_ip_mroute.template
Labels: changes_requested

#378 Cisco xr show route vrf all
  templates/cisco_xr_show_ip_route.template
  templates/index
  tests/cisco_xr/show_ip_route/cisco_xr_show_ip_route.parsed
  tests/cisco_xr/show_ip_route/cisco_xr_show_ip_route2.parsed
  tests/cisco_xr/show_ip_route/cisco_xr_show_ip_route_vrf.parsed
  tests/cisco_xr/show_ip_route/cisco_xr_show_ip_route_vrf.raw
Labels: PR Submitted, changes_requested, enhancement

#425 add cisco_wlc_ssh_show_exclusionlist
  templates/cisco_wlc_ssh_show_exclusionlist.template
  templates/index
  tests/cisco_wlc_ssh/show_exclusionlist/cisco_wlc_ssh_show_exclusionlist.parsed
  tests/cisco_wlc_ssh/show_exclusionlist/cisco_wlc_ssh_show_exclusionlist.raw
Labels: changes_requested

#471 fixed ports
  templates/hp_procurve_show_arp.template
  tests/hp_procurve/show_arp/hp_procurve_show_arp_1.parsed
  tests/hp_procurve/show_arp/hp_procurve_show_arp_1.raw
Labels: bug, changes_requested

#478 Add template cisco_nxos_show_ip_interface_brief
  templates/cisco_nxos_show_ip_interface_brief.template
  templates/index
  tests/cisco_nxos/show_ip_interface_brief/cisco_nxos_show_ip_interface_brief.parsed
  tests/cisco_nxos/show_ip_interface_brief/cisco_nxos_show_ip_interface_brief.raw
Labels: New Template, changes_requested

#479 Issue 472 patch
  templates/cisco_nxos_show_interface_brief.template
  tests/cisco_nxos/show_interface_brief/cisco_nxos_show_interface_brief.parsed
  tests/cisco_nxos/show_interface_brief/cisco_nxos_show_interface_brief.raw
Labels: bug, changes_requested
