Repository networktocode/ntc-templates, pull requests merged in 2020-12, with the labels that each got.

#827 New template: dell_powerconnect
  templates/dell_powerconnect_show_bridge_address_table.textfsm
  templates/dell_powerconnect_show_interfaces_description.textfsm
  templates/dell_powerconnect_show_interfaces_status.textfsm
  templates/index
  tests/dell_powerconnect/show_bridge_address_table/dell_powerconnect_show_bridge_address_table.raw
  tests/dell_powerconnect/show_bridge_address_table/dell_powerconnect_show_bridge_address_table.yml
  tests/dell_powerconnect/show_interfaces_description/dell_powerconnect_show_interfaces_description.raw
  tests/dell_powerconnect/show_interfaces_description/dell_powerconnect_show_interfaces_description.yml
  tests/dell_powerconnect/show_interfaces_status/dell_powerconnect_show_interfaces_status.raw
  tests/dell_powerconnect/show_interfaces_status/dell_powerconnect_show_interfaces_status.yml
  tests/test_index_order.py
Labels: changes_requested

#829 New Template: hp_procurve_show_interfaces_brief.textfsm
  templates/hp_procurve_show_interfaces_brief.textfsm
  templates/index
  tests/hp_procurve/show_interfaces_brief/show_interfaces_brief.raw
  tests/hp_procurve/show_interfaces_brief/show_interfaces_brief.yml
  tests/hp_procurve/show_interfaces_brief/show_interfaces_brief_bcast.raw
  tests/hp_procurve/show_interfaces_brief/show_interfaces_brief_bcast.yml
Labels: New Template

#832 added fortinet get system arp
  templates/fortinet_get_system_arp.textfsm
  templates/index
  tests/fortinet/get_system_arp/fortinet_get_system_arp.raw
  tests/fortinet/get_system_arp/fortinet_get_system_arp.yml
Labels: New Template, changes_requested

#839 Fix#788 ios show int fc
  templates/cisco_ios_show_interfaces_status.textfsm
  tests/cisco_ios/show_interfaces_status/cisco_ios_show_interfaces_status.yml
  tests/cisco_ios/show_interfaces_status/cisco_ios_show_interfaces_status2.raw
  tests/cisco_ios/show_interfaces_status/cisco_ios_show_interfaces_status2.yml
Labels: changes_requested

#838 Fixes #790 - new template cisco_nxos_show_environment.textfsm
  templates/cisco_nxos_show_environment.textfsm
  templates/cisco_nxos_show_environments.textfsm
  templates/index
  tests/cisco_nxos/show_environment/cisco_nxos_show_environment.raw
  tests/cisco_nxos/show_environment/cisco_nxos_show_environment.yml
  tests/cisco_nxos/show_environment/cisco_nxos_show_environment2.raw
  tests/cisco_nxos/show_environment/cisco_nxos_show_environment2.yml
Labels: changes_requested
