Repository networktocode/ntc-templates, pull requests merged in 2020-06, with the labels that each got.

#734 Fixes missing interfaces on down interfaces
  templates/cisco_asa_show_interface.textfsm
  tests/cisco_asa/show_interface/cisco_asa_show_interface1.raw
  tests/cisco_asa/show_interface/cisco_asa_show_interface1.yml
Labels: bug, changes_requested

#722 New Template for Cisco NX-OS: show forwarding adjacency
  templates/cisco_nxos_show_forwarding_adjacency.textfsm
  templates/index
  tests/cisco_nxos/show_forwarding_adjacency/cisco_nxos_show_forwarding_adjacency_1.raw
  tests/cisco_nxos/show_forwarding_adjacency/cisco_nxos_show_forwarding_adjacency_1.yml
  tests/cisco_nxos/show_forwarding_adjacency/cisco_nxos_show_forwarding_adjacency_2.raw
  tests/cisco_nxos/show_forwarding_adjacency/cisco_nxos_show_forwarding_adjacency_2.yml
  tests/cisco_nxos/show_forwarding_adjacency/cisco_nxos_show_forwarding_adjacency_3.raw
  tests/cisco_nxos/show_forwarding_adjacency/cisco_nxos_show_forwarding_adjacency_3.yml
Labels: changes_requested

#732 New template for ubiquity edgeswitch: show version
  templates/index
  templates/ubiquiti_edgeswitch_show_version.textfsm
  tests/ubiquiti_edgeswitch/show_version/ubiquiti_edgeswitch_show_version.raw
  tests/ubiquiti_edgeswitch/show_version/ubiquiti_edgeswitch_show_version.yml
  tests/ubiquiti_edgeswitch/show_version/ubiquiti_edgeswitch_show_version2.raw
  tests/ubiquiti_edgeswitch/show_version/ubiquiti_edgeswitch_show_version2.yml
Labels: changes_requested

#733 New Template support for broadcom_icos as a new OS and added show_version command
  templates/broadcom_icos_show_version.textfsm
  templates/index
  tests/broadcom_icos/show_version/broadcom_icos_show_version.raw
  tests/broadcom_icos/show_version/broadcom_icos_show_version.yml
  tests/broadcom_icos/show_version/broadcom_icos_show_version2.raw
  tests/broadcom_icos/show_version/broadcom_icos_show_version2.yml
  tests/broadcom_icos/show_version/broadcom_icos_show_version3.raw
  tests/broadcom_icos/show_version/broadcom_icos_show_version3.yml
  tests/broadcom_icos/show_version/broadcom_icos_show_version4.raw
  tests/broadcom_icos/show_version/broadcom_icos_show_version4.yml
  tests/broadcom_icos/show_version/broadcom_icos_show_version5.raw
  tests/broadcom_icos/show_version/broadcom_icos_show_version5.yml
  tests/test_index_order.py
Labels: New Template, changes_requested

#671 BugFix: cisco_ios_show_interfaces_switchport: Made trunking_vlans a list, and changed regex
  templates/cisco_ios_show_interfaces_switchport.textfsm
  tests/cisco_ios/show_interfaces_switchport/cisco_ios_show_interfaces_switchport.yml
  tests/cisco_ios/show_interfaces_switchport/cisco_ios_show_interfaces_switchport2.raw
  tests/cisco_ios/show_interfaces_switchport/cisco_ios_show_interfaces_switchport2.yml
  tests/cisco_ios/show_interfaces_switchport/cisco_ios_show_interfaces_switchport_ethertype.yml
  tests/cisco_ios/show_interfaces_switchport/cisco_ios_show_interfaces_switchport_vepa_enabled.yml
  tests/cisco_ios/show_interfaces_switchport/cisco_ios_show_interfaces_switchport_voice_vlan.yml
Labels: changes_requested

#736 Added support for broadcom_icos command show_mac-address-table
  templates/broadcom_icos_show_mac-address-table.textfsm
  templates/index
  tests/broadcom_icos/show_mac-address-table/broadcom_show_mac-address-table.raw
  tests/broadcom_icos/show_mac-address-table/broadcom_show_mac-address-table.yml
Labels: changes_requested

#744 Added interfaces to arista_eos_show_vrf template
  templates/arista_eos_show_vrf.textfsm
  tests/arista_eos/show_vrf/arista_eos_show_vrf.raw
  tests/arista_eos/show_vrf/arista_eos_show_vrf.yml
  tests/arista_eos/show_vrf/arista_eos_show_vrf_2.raw
  tests/arista_eos/show_vrf/arista_eos_show_vrf_2.yml
Labels: changes_requested

#748 New Template added support for broadcom_icos_show_isdp_neighbors
  templates/broadcom_icos_show_isdp_neighbors.textfsm
  templates/index
  tests/broadcom_icos/show_isdp_neighbors/broadcom_icos_show_isdp_neighbors.raw
  tests/broadcom_icos/show_isdp_neighbors/broadcom_icos_show_isdp_neighbors.yml
Labels: changes_requested

#749 New Template added support for broadcom_icos_show_lldp_remote-device_all
  templates/broadcom_icos_show_lldp_remote-device_all.textfsm
  templates/index
  tests/broadcom_icos/show_lldp_remote-device_all/broadcom_icos_show_lldp_remote-device_all.raw
  tests/broadcom_icos/show_lldp_remote-device_all/broadcom_icos_show_lldp_remote-device_all.yml
Labels: changes_requested

#750 New Template added support for broadcom_icos_show_vlan_brief
  templates/broadcom_icos_show_vlan_brief.textfsm
  templates/index
  tests/broadcom_icos/show_vlan_brief/broadcom_icos_show_vlan_brief.raw
  tests/broadcom_icos/show_vlan_brief/broadcom_icos_show_vlan_brief.yml
Labels: changes_requested

#756 Arista eos show mac address table
  templates/arista_eos_show_mac_address-table.textfsm
  tests/arista_eos/show_mac_address-table/arista_eos_show_mac_address-table.raw
  tests/arista_eos/show_mac_address-table/arista_eos_show_mac_address-table.yml
Labels: changes_requested

#757 Arista eos show port channel summary
  templates/arista_eos_show_port-channel_summary.textfsm
  templates/index
  tests/arista_eos/show_port-channel_summary/arista_eos_show_port-channel_summary.raw
  tests/arista_eos/show_port-channel_summary/arista_eos_show_port-channel_summary.yml
Labels: changes_requested

#758 New Template: cisco_nxos_show_interface_description
  templates/cisco_nxos_show_interface_description.textfsm
  templates/index
  tests/cisco_nxos/show_interface_description/cisco_nxos_show_interface_description.raw
  tests/cisco_nxos/show_interface_description/cisco_nxos_show_interface_description.yml
Labels: changes_requested

#761 New Template: cisco_nxos_show_ip_interface
  templates/cisco_nxos_show_ip_interface.textfsm
  templates/index
  tests/cisco_nxos/show_ip_interface/cisco_nxos_show_ip_interface.raw
  tests/cisco_nxos/show_ip_interface/cisco_nxos_show_ip_interface.yml
Labels: changes_requested

#759 New Template: cisco_nxos_show_license_usage
  templates/cisco_nxos_show_license_usage.textfsm
  templates/index
  tests/cisco_nxos/show_license_usage/cisco_nxos_show_license_usage.raw
  tests/cisco_nxos/show_license_usage/cisco_nxos_show_license_usage.yml
Labels: changes_requested

#760 New Template: cisco_nxos_show_hsrp_all
  templates/cisco_nxos_show_hsrp_all.textfsm
  templates/index
  tests/cisco_nxos/show_hsrp_all/cisco_nxos_show_hsrp_all.raw
  tests/cisco_nxos/show_hsrp_all/cisco_nxos_show_hsrp_all.yml
Labels: changes_requested
