Repository networktocode/ntc-templates, pull requests merged in 2020-01, with the labels that each got.

#577 Bug Fix for cisco ios show mac address-table parser
  templates/cisco_ios_show_mac-address-table.textfsm
  tests/cisco_ios/show_mac-address-table/cisco_ios_show_mac-address-table7.raw
  tests/cisco_ios/show_mac-address-table/cisco_ios_show_mac-address-table7.yml
Labels: changes_requested

#580 New Template Pull Request - cisco_xr_show_interfaces_summary
  templates/cisco_xr_show_interfaces_summary.textfsm
  templates/index
  tests/cisco_xr/show_interfaces_summary/cisco_xr_show_interfaces_summary.raw
  tests/cisco_xr/show_interfaces_summary/cisco_xr_show_interfaces_summary.yml
Labels: New Template, changes_requested

#584 BugFix: Cisco show switch detail with mac persistency wait time
  templates/cisco_ios_show_switch_detail.textfsm
  tests/cisco_ios/show_switch_detail/cisco_ios_show_switch_detail3.raw
  tests/cisco_ios/show_switch_detail/cisco_ios_show_switch_detail3.yml
Labels: bug, changes_requested
