Repository networktocode/ntc-templates, pull requests merged in 2022-12, with the labels that each got.

#1235 Update icon, fix issue with missing page, make support model more clear
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  docs/images/icon-ntc-templates.png
  docs/user/faq.md
  docs/user/lib_use_case.md
Labels: josh-review

#1147 Add aruba_os show ap bss-table details
  ntc_templates/templates/aruba_os_show_ap_bss-table_details.textfsm
  ntc_templates/templates/index
  tests/aruba_os/show_ap_bss-table_details/aruba_os_show_ap_bss-table_details.raw
  tests/aruba_os/show_ap_bss-table_details/aruba_os_show_ap_bss-table_details.yml
Labels: ken-review

#1230 Fix cisco ipv6 neighbors
  ntc_templates/templates/cisco_ios_show_ipv6_neighbors.textfsm
  tests/cisco_ios/show_ipv6_neighbors/cisco_ios_show_ipv6_neighbors1.raw
  tests/cisco_ios/show_ipv6_neighbors/cisco_ios_show_ipv6_neighbors1.yml
Labels: josh-review

#1053 juniper: add SRX and XE support to show version
  ntc_templates/templates/juniper_junos_show_version.textfsm
  tests/juniper_junos/show_version/juniper_junos_show_version.yml
  tests/juniper_junos/show_version/juniper_junos_show_version_ex.raw
  tests/juniper_junos/show_version/juniper_junos_show_version_ex.yml
  tests/juniper_junos/show_version/juniper_junos_show_version_srx_cluster.raw
  tests/juniper_junos/show_version/juniper_junos_show_version_srx_cluster.yml
Labels: jacob-review

#1041 Fixs_1009_fortinet_get_system_ha_status.textfsm
  ntc_templates/templates/fortinet_get_system_ha_status.textfsm
  tests/fortinet/get_system_ha_status/fortinet_get_system_ha_status_6.4.raw
  tests/fortinet/get_system_ha_status/fortinet_get_system_ha_status_6.4.yml
Labels: jacob-review

#1040 fix1037_paloalto_panos_show_running_nat-policy
  ntc_templates/templates/paloalto_panos_show_running_nat-policy.textfsm
  tests/paloalto_panos/show_running_nat-policy/paloalto_panos_show_running_nat-policy1.raw
  tests/paloalto_panos/show_running_nat-policy/paloalto_panos_show_running_nat-policy1.yml
  tests/paloalto_panos/show_running_nat-policy/paloalto_panos_show_running_nat-policy2.raw
  tests/paloalto_panos/show_running_nat-policy/paloalto_panos_show_running_nat-policy2.yml
Labels: jacob-review

#1159 fix(Mikrotik): Optional space before end of line
  ntc_templates/templates/mikrotik_routeros_ip_arp_print_without-paging.textfsm
  ntc_templates/templates/mikrotik_routeros_ip_dhcp-server_lease_print_without-paging.textfsm
  ntc_templates/templates/mikrotik_routeros_ip_firewall_filter_print_all_without-paging.textfsm
  ntc_templates/templates/mikrotik_routeros_ip_firewall_nat_print_all_without-paging.textfsm
  ntc_templates/templates/mikrotik_routeros_snmp_community_print_without-paging.textfsm
Labels: jacob-review

#1265 Add support for Ericsson IPOS router
  ntc_templates/templates/ericsson_ipos_show_arp.textfsm
  ntc_templates/templates/ericsson_ipos_show_isis_adjacency.textfsm
  ntc_templates/templates/ericsson_ipos_show_version.textfsm
  ntc_templates/templates/index
  tests/ericsson_ipos/show_arp/ericsson_ipos_show_arp.raw
  tests/ericsson_ipos/show_arp/ericsson_ipos_show_arp.yml
  tests/ericsson_ipos/show_arp/ericsson_ipos_show_arp_all-context.raw
  tests/ericsson_ipos/show_arp/ericsson_ipos_show_arp_all-context.yml
  tests/ericsson_ipos/show_arp/ericsson_ipos_show_arp_all.raw
  tests/ericsson_ipos/show_arp/ericsson_ipos_show_arp_all.yml
  tests/ericsson_ipos/show_isis_adjacency/ericsson_ipos_show_isis_adjacency.raw
  tests/ericsson_ipos/show_isis_adjacency/ericsson_ipos_show_isis_adjacency.yml
  tests/ericsson_ipos/show_version/ericsson_ipos_show_version.raw
  tests/ericsson_ipos/show_version/ericsson_ipos_show_version.yml
  tests/test_index_order.py
Labels: ken-review

#1266 add display_arp_all and display_isis_peer
  ntc_templates/templates/huawei_vrp_display_arp_all.textfsm
  ntc_templates/templates/huawei_vrp_display_isis_peer.textfsm
  ntc_templates/templates/index
  tests/huawei_vrp/display_arp_all/huawei_vrpv8_display_arp_all.raw
  tests/huawei_vrp/display_arp_all/huawei_vrpv8_display_arp_all.yml
  tests/huawei_vrp/display_isis_peer/huawei_vrpv8_display_isis_peer.raw
  tests/huawei_vrp/display_isis_peer/huawei_vrpv8_display_isis_peer.yml
Labels: ken-review

#1267 Add support DLink DS Show ARP
  ntc_templates/templates/dlink_ds_show_arpentry.textfsm
  ntc_templates/templates/index
  tests/dlink_ds/show_arpentry/dlink_ds_show_arpentry.raw
  tests/dlink_ds/show_arpentry/dlink_ds_show_arpentry.yml
  tests/test_index_order.py
Labels: ken-review

#1151 Zyxel fix sys atsh parsing
  ntc_templates/templates/zyxel_os_sys_atsh.textfsm
  tests/zyxel_os/sys_atsh/zyxel_os_sys_atsh2.raw
  tests/zyxel_os/sys_atsh/zyxel_os_sys_atsh2.yml
Labels: ken-review

#1132 Update hp_comware_display_device_manuinfo.textfsm
  ntc_templates/templates/hp_comware_display_device_manuinfo.textfsm
  tests/hp_comware/display_device_manuinfo/hp_comware_display_device_manuinfo4.raw
  tests/hp_comware/display_device_manuinfo/hp_comware_display_device_manuinfo4.yml
Labels: ken-review
