Repository networktocode/ntc-templates, pull requests merged in 2023-03, with the labels that each got.

#1172 Mikrotik routeros - firewall filter - Add src mac address, correct ipv6 path and empty log prefix
  ntc_templates/templates/index
  ntc_templates/templates/mikrotik_routeros_ip_firewall_filter_print_all_without-paging.textfsm
  tests/mikrotik_routeros/ip_firewall_filter_print_all_without-paging/mikrotik_routeros_ip_firewall_filter_print_all_without-paging.raw
  tests/mikrotik_routeros/ip_firewall_filter_print_all_without-paging/mikrotik_routeros_ip_firewall_filter_print_all_without-paging.yml
Labels: changes_requested, josh-review

#1290 Added new template: show interface link on cisco ios
  ntc_templates/templates/cisco_ios_show_interface_link.textfsm
  ntc_templates/templates/index
  tests/cisco_ios/show_interface_link/cisco_ios_show_interface_link.raw
  tests/cisco_ios/show_interface_link/cisco_ios_show_interface_link.yml
  tests/cisco_ios/show_interface_link/cisco_ios_show_interface_link2.raw
  tests/cisco_ios/show_interface_link/cisco_ios_show_interface_link2.yml
Labels: changes_requested

#1222 Fix huawei display acl all - port numbers replaced by names and IPV6 ACL name position
  ntc_templates/templates/huawei_vrp_display_acl_all.textfsm
  tests/huawei_vrp/display_acl_all/huawei_vrp_display_acl_all_1.raw
  tests/huawei_vrp/display_acl_all/huawei_vrp_display_acl_all_1.yml
  tests/huawei_vrp/display_acl_all/huawei_vrp_display_acl_ipv6_all_1.raw
  tests/huawei_vrp/display_acl_all/huawei_vrp_display_acl_ipv6_all_1.yml
Labels: patryk-review
