Repository networktocode/ntc-templates, pull requests merged in 2024-08, with the labels that each got.

#1501 MikroTik RouterOS 'interface ethernet monitor name once' extend templatewith new values
  ntc_templates/templates/mikrotik_routeros_interface_ethernet_monitor_name_once.textfsm
  tests/mikrotik_routeros/interface_ethernet_monitor_name_once/mikrotik_routeros_interface_ethernet_monitor_name_once.yml
  tests/mikrotik_routeros/interface_ethernet_monitor_name_once/mikrotik_routeros_interface_ethernet_monitor_name_once2.yml
  tests/mikrotik_routeros/interface_ethernet_monitor_name_once/mikrotik_routeros_interface_ethernet_monitor_name_once3.raw
  tests/mikrotik_routeros/interface_ethernet_monitor_name_once/mikrotik_routeros_interface_ethernet_monitor_name_once3.yml
Labels: status: gathering feedback

#1808 Fix Mikrotik's '/ip neighbor print detail' template
  ntc_templates/templates/mikrotik_routeros_ip_neighbor_print_detail.textfsm
  tests/mikrotik_routeros/ip_neighbor_print_detail/mikrotik_routeros_ip_neighbor_print_detail.yml
  tests/mikrotik_routeros/ip_neighbor_print_detail/mikrotik_routeros_ip_neighbor_print_detail_ipv6.raw
  tests/mikrotik_routeros/ip_neighbor_print_detail/mikrotik_routeros_ip_neighbor_print_detail_ipv6.yml
  tests/mikrotik_routeros/ip_neighbor_print_detail/mikrotik_routeros_ip_neighbor_print_detail_line_wrap.raw
  tests/mikrotik_routeros/ip_neighbor_print_detail/mikrotik_routeros_ip_neighbor_print_detail_line_wrap.yml
Labels: changes_requested

#1812 Fix template for Eltex's command 'show interfaces description'
  ntc_templates/templates/eltex_show_interfaces_description.textfsm
  tests/eltex/show_interfaces_description/show_interfaces_description_1.yml
  tests/eltex/show_interfaces_description/show_interfaces_description_2.raw
  tests/eltex/show_interfaces_description/show_interfaces_description_2.yml
  tests/eltex/show_interfaces_description/show_interfaces_description_3.yml
Labels: breaking_change

#1820 s300 lldp neighbors allow for multiline values
  ntc_templates/templates/cisco_s300_show_lldp_neighbors.textfsm
  tests/cisco_s300/show_lldp_neighbors/cisco_s300_show_lldp_neighbors.yml
  tests/cisco_s300/show_lldp_neighbors/cisco_s300_show_lldp_neighbors_multiline.raw
  tests/cisco_s300/show_lldp_neighbors/cisco_s300_show_lldp_neighbors_multiline.yml
Labels: breaking_change
