Repository networktocode/ntc-templates, pull requests merged in 2025-04, with the labels that each got.

#2013 Fix protocol spelling in hp_comware disp ip interface
  ntc_templates/templates/hp_comware_display_ip_routing-table.textfsm
  tests/hp_comware/display_ip_routing-table/hp_comware_display_ip_routing-table.yml
Labels: breaking_change

#1983 Fix lowercase capture groups
  ntc_templates/templates/brocade_fastiron_show_interfaces.textfsm
  ntc_templates/templates/brocade_fastiron_show_interfaces_brief.textfsm
  ntc_templates/templates/brocade_fastiron_show_lag_brief.textfsm
  ntc_templates/templates/brocade_fastiron_show_metro.textfsm
  ntc_templates/templates/brocade_fastiron_show_monitor.textfsm
  ntc_templates/templates/brocade_fastiron_show_running-config_vlan.textfsm
  ntc_templates/templates/brocade_fastiron_show_span.textfsm
  ntc_templates/templates/brocade_fastiron_show_topo.textfsm
  ntc_templates/templates/brocade_netiron_show_interfaces.textfsm
  ntc_templates/templates/brocade_netiron_show_interfaces_brief.textfsm
  ntc_templates/templates/brocade_netiron_show_lag_brief.textfsm
  ntc_templates/templates/brocade_netiron_show_metro.textfsm
  ntc_templates/templates/brocade_netiron_show_monitor_actual.textfsm
  ntc_templates/templates/brocade_netiron_show_running-config_vlan.textfsm
  ntc_templates/templates/brocade_netiron_show_span.textfsm
  ntc_templates/templates/brocade_netiron_show_topo.textfsm
  ntc_templates/templates/cisco_asa_show_running-config_all_crypto_map.textfsm
  ntc_templates/templates/cisco_ios_show_alert_counters.textfsm
  ntc_templates/templates/cisco_xr_show_lldp_neighbors_detail.textfsm
  ntc_templates/templates/cisco_xr_show_processes_cpu.textfsm
  ntc_templates/templates/oneaccess_oneos_show_voice_voice-port_pri_all.textfsm
  tests/brocade_fastiron/show_interfaces/brocade_fastiron_show_interfaces.yml
  tests/brocade_fastiron/show_interfaces/brocade_fastiron_show_interfaces1.yml
  tests/brocade_fastiron/show_interfaces_brief/brocade_fastiron_show_interfaces_brief.yml
  tests/brocade_fastiron/show_interfaces_brief/brocade_fastiron_show_interfaces_brief1.yml
  tests/brocade_fastiron/show_interfaces_brief/brocade_fastiron_show_interfaces_brief2.yml
  tests/brocade_fastiron/show_lag_brief/brocade_fastiron_show_lag_brief.yml
  tests/brocade_fastiron/show_metro/brocade_fastiron_show_metro.yml
  tests/brocade_fastiron/show_metro/brocade_fastiron_show_metro1.yml
  tests/brocade_fastiron/show_monitor/brocade_fastiron_show_monitor.yml
  tests/brocade_fastiron/show_running-config_vlan/brocade_fastiron_show_running-config_vlan.yml
  tests/brocade_fastiron/show_running-config_vlan/brocade_fastiron_show_running-config_vlan1.yml
  tests/brocade_fastiron/show_span/brocade_fastiron_show_span.yml
  tests/brocade_fastiron/show_span/brocade_fastiron_show_span1.yml
  tests/brocade_fastiron/show_topo/brocade_fastiron_show_topo.yml
  tests/brocade_fastiron/show_topo/brocade_fastiron_show_topo1.yml
  tests/brocade_netiron/show_interfaces/brocade_netiron_show_interfaces.yml
  tests/brocade_netiron/show_interfaces_brief/brocade_netiron_show_interfaces_brief.yml
  tests/brocade_netiron/show_lag_brief/brocade_netiron_show_lag_brief.yml
  tests/brocade_netiron/show_metro/brocade_netiron_show_metro.yml
  tests/brocade_netiron/show_monitor_actual/brocade_netiron_show_monitor.yml
  tests/brocade_netiron/show_running-config_vlan/brocade_netiron_show_running-config_vlan.yml
  tests/brocade_netiron/show_span/brocade_netiron_show_span.yml
  tests/brocade_netiron/show_topo/brocade_netiron_show_topo.yml
  tests/cisco_ios/show_alert_counters/cisco_ios_show_alert_counters.yml
  tests/test_capture_group_case.py
Labels: breaking_change

#2081 Update Linux ip route show
  ntc_templates/templates/linux_ip_route_show.textfsm
  tests/linux/ip_route_show/linux_ip_route_show.yml
  tests/linux/ip_route_show/linux_ip_route_show2.raw
  tests/linux/ip_route_show/linux_ip_route_show2.yml
  tests/linux/ip_route_show/linux_ip_route_show_linkdown.raw
  tests/linux/ip_route_show/linux_ip_route_show_linkdown.yml
Labels: WIP

#1984 Normalize vlan id and name stragglers
  docs/dev/data_model.md
  ntc_templates/templates/brocade_fastiron_show_running-config_vlan.textfsm
  ntc_templates/templates/brocade_fastiron_show_span.textfsm
  ntc_templates/templates/brocade_netiron_show_running-config_vlan.textfsm
  ntc_templates/templates/cisco_ios_show_ip_dhcp_snooping_binding.textfsm
  ntc_templates/templates/cisco_s300_show_interfaces_switchport.textfsm
  ntc_templates/templates/eltex_show_interfaces_switchport.textfsm
  ntc_templates/templates/extreme_exos_show_iparp.textfsm
  ntc_templates/templates/huawei_smartax_display_mac-address_ont_0_1_2_0.textfsm
  tests/brocade_fastiron/show_running-config_vlan/brocade_fastiron_show_running-config_vlan.yml
  tests/brocade_fastiron/show_running-config_vlan/brocade_fastiron_show_running-config_vlan1.yml
  tests/brocade_fastiron/show_span/brocade_fastiron_show_span.yml
  tests/brocade_fastiron/show_span/brocade_fastiron_show_span1.yml
  tests/brocade_netiron/show_running-config_vlan/brocade_netiron_show_running-config_vlan.yml
  tests/cisco_ios/show_ip_dhcp_snooping_binding/provided_output.yml
  tests/cisco_s300/show_interfaces_switchport/cisco_s300_show_interfaces_switchport.yml
  tests/eltex/show_interfaces_switchport/show_interfaces_switchport_1.yml
  tests/eltex/show_interfaces_switchport/show_interfaces_switchport_2.yml
  tests/extreme_exos/show_iparp/extreme_exos_show_iparp.yml
  tests/extreme_exos/show_iparp/extreme_exos_show_iparp_online_data.yml
  tests/huawei_smartax/display_mac-address_ont_0_1_2_0/huawei_smartax_display_mac-address_ont_0_1_2_0.yml
  tests/huawei_smartax/display_mac-address_ont_0_1_2_0/huawei_smartax_display_mac-address_ont_0_1_2_0_2.yml
Labels: breaking_change

#2091 Add Huawei VRP display bgp peer template
  ntc_templates/templates/huawei_vrp_display_bgp_peer.textfsm
  ntc_templates/templates/index
  tests/huawei_vrp/display_bgp_peer/huawei_vrp_display_bgp_peer.raw
  tests/huawei_vrp/display_bgp_peer/huawei_vrp_display_bgp_peer.yml
  tests/huawei_vrp/display_bgp_peer/huawei_vrp_display_bgp_peer2.raw
  tests/huawei_vrp/display_bgp_peer/huawei_vrp_display_bgp_peer2.yml
Labels: question, status: action required
